language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t edmorra/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true edmorra/docker-react npm run test -- --coverage
